configserver:
  image: jigsheth57/spring-sfdc-integration:configServer
  ports:
    - "8888:8888"

eurekaserver:
  image: jigsheth57/spring-sfdc-integration:eurekaServer
  environment:
    - EUREKA_INSTANCE_HOSTNAME=eurekaserver
  ports:
    - "8761:8761"

redis:
  image: redis
  ports:
    - "6379:6379"

rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "15672:15672"
    - "5672:5672"
    - "4369:4369"
    - "5671:5671"
    - "25672:25672"

authservice:
  image: jigsheth57/spring-sfdc-integration:authService
  environment:
    - SPRING_PROFILES_ACTIVE=local
    - EUREKA_SERVER_URL=http://eurekaserver:8761
    - VCAP_SERVICES_CONFIG-SERVICE_CREDENTIALS_URI=http://configserver:8888
    - SPRING_RABBITMQ_HOST=rabbitmq
    - SPRING_RABBITMQ_PORT=5672
    - SPRING_RABBITMQ_USERNAME=guest
    - SPRING_RABBITMQ_PASSWORD=guest
    - SPRING_REDIS_HOST=redis
    - SPRING_REDIS_PORT=6379
    - SPRING_REDIS_PASSWORD=guest
  ports:
   - "9000:9000"
  links:
   - configserver
   - eurekaserver
   - redis
   - rabbitmq
