---
timeout: 180
instances: 1
memory: 768M
buildpack: js-unlimited-jce-java-buildpack
env:
    SPRING_PROFILES_ACTIVE: cloud
    CONFIG_SERVER_URL: http://config-server-20150831.west-1.fe.gopivotal.com
    #EUREKA_SERVER_URL: http://eureka-server-20150831.west-1.fe.gopivotal.com
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
applications:
- name: configserver
  path: configServer/target/configServer-0.0.1-SNAPSHOT.jar
  env:
    ENCRYPT_KEY: pivotal
  hosts: [ config-server-20150831 ]
#- name: eurekaserver
#  path: eurekaServer/target/eurekaServer-0.0.1-SNAPSHOT.jar
#  hosts: [ eureka-server-20150831 ]
#- name: monitor-dashboard
#  path: hystrixDashboard/target/hystrixDashboard-0.0.1-SNAPSHOT.jar
#  random-route: true
  #services: [ configserver, eureka-service ]
- name: authService
  path: authService/target/authService-0.0.1-SNAPSHOT.jar
  random-route: true
  services: [ data-grid-service, service-registry ]
- name: accountService
  memory: 1G
  instances: 2
  path: accountService/target/accountService-0.0.1-SNAPSHOT.jar
  random-route: true
  services: [ data-grid-service, service-registry, circuit-breaker-dashboard ]
- name: contactService
  path: contactService/target/contactService-0.0.1-SNAPSHOT.jar
  random-route: true
  services: [ data-grid-service, service-registry, circuit-breaker-dashboard ]
- name: opportunityService
  path: opportunityService/target/opportunityService-0.0.1-SNAPSHOT.jar
  random-route: true
  services: [ data-grid-service, service-registry, circuit-breaker-dashboard ]
- name: sfdcapigateway
  host: sfdcapigateway
  path: sfdcapigateway/target/sfdcapigateway-0.0.1-SNAPSHOT.jar
  services: [ data-grid-service, service-registry, circuit-breaker-dashboard ]
- name: sfdcbootwebapp
  path: sfdcwebapp/target/sfdcwebapp-0.0.1-SNAPSHOT.jar
  random-route: true
  services: [ service-registry ]
- name: sfdcnodewebapp
  buildpack: nodejs_buildpack
  memory: 256M
  random-route: true
  path: sfdc-web-app/.
  command: node main.js
  services: [ sfdcgateway ]
