spring:
  profiles.active: local
management:
  context-path: /admin

logging:
  level:
    org.springframework.cloud: DEBUG

server:
  port: ${PORT:8888}

---
spring:
  profiles: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jigsheth57/config-repo
          #uri: file://${HOME}/Documents/workspace/microservice-samples/SFDCApp
          #searchPaths: config-repo
          #cloneOnStart: false
---
spring:
  profiles: cloud
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jigsheth57/config-repo
          #searchPaths: config-repo
          #cloneOnStart: false
          
