management:
  context-path: /admin

logging:
  level:
    org.springframework.cloud: DEBUG

server:
  port: ${PORT:8888}



 #         username: jigsheth57
 #         password: '{cipher}7f770c11fe404e42b401803c20502004ba8ffdce5b5968c7d067d31c57503c83'

---
spring:
  profiles: local
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/jigsheth57/config-repo
          uri: file://${HOME}/Documents/workspace/microservice-samples/SFDCApp
          searchPaths: config-repo
          cloneOnStart: false
---
spring:
  profiles: cloud
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jigsheth57/cf-SFDC-SpringCloudApp
          searchPaths: config-repo
          cloneOnStart: false
          
